# Load in NumPy (Remember to pip install numpy first )

In [1]:
import numpy as np

# The basics

In [11]:
a = np.array([1,2,3], dtype='int16') # specify the datatype for increasing the efficiency
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get the dimensions of your numpy array
print(" dimensions of a : ", a.ndim) # no of dimensions
print(" dimensions of b : ", b.ndim)

 dimensions of a :  1
 dimensions of b :  2


In [6]:
# get the shape
print(" shape of a : ", a.shape)
print(" shape of b : ", b.shape)

 shape of a :  (3,)
 shape of b :  (2, 3)


In [7]:
# get the data type
print(" data type of a : ", a.dtype)
print(" data type of b : ", b.dtype)


 data type of a :  int16
 data type of b :  float64


In [8]:
# get the size
print(" item size of a : ",a.itemsize)
print(" item size of b : ",b.itemsize)

 item size of a :  2
 item size of b :  8


In [9]:
# get the total size
print(" total size of a : ", a.itemsize * a.size) 
print(" total size of b : ", b.nbytes) # same as b.itemsize * b.size

 total size of a :  6
 total size of b :  48


# Accessing/Changing specific elements, rows, columns, etc.

In [4]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])   # 2 by 7 
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
c.shape

(2, 7)

In [6]:
# get a specific element [row, column]
print(c[1, 5])
print(c[1 ,-2])

13
13


In [7]:
# get a specific row  
c[0, :] # gets a specific single row

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# get a specific column 
c[: ,1]  #second element from each row

array([2, 9])

In [9]:
#getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2] # goes to first row, gives all second element from index 1 till index 6

array([2, 4, 6])

In [33]:
c[0, 1:-1: 2] #just does the same thing but backwards (no elements)

array([2, 4, 6])

In [35]:
# editing the array row
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [10]:
# editing the array column (with a single value, and then with a sequence)
c[:, 2] = 5
print(c, '\n')

print("replacing with a sequence : \n ")
c[:, 2] = [1,2]
print(c)


[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]] 

replacing with a sequence : 
 
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


# A 3d example

In [6]:
d = np.array([ [[1,2], [3,4]] , [[5,6], [7,8]] ])  
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
# get a specific element (work outside in)

# trying to get '4'
print(d[0,1,1], '\n')

#trying to get 3,4,7,8 (visualize in 3-d then you would get it)
print(d[:,1,:])

4 

[[3 4]
 [7 8]]


In [53]:
# editing a 3d array
d[:,1,:] = [ [9,16], [49, 64] ]   # SHOULD WORK FINE IF ITS THE SAME DIMENSION
print(d)

[[[ 1  2]
  [ 9 16]]

 [[ 5  6]
  [49 64]]]


 # Initializing different types of arrays

In [55]:
# All Zeros(0s) matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
# ALL ones matrix
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [58]:
# Any other number
np.full((2,2) , 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [7]:
# Any other number (full_like)
np.full_like(d, 7)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [64]:
# Ramdom decimal numbers
np.random.rand(2,3,3)

array([[[0.13759918, 0.35780618, 0.69207431],
        [0.43774035, 0.27330291, 0.70961966],
        [0.88527099, 0.51348441, 0.06593438]],

       [[0.85970139, 0.84791585, 0.37253478],
        [0.95459925, 0.98067151, 0.48016273],
        [0.7166262 , 0.62328552, 0.09832234]]])

In [66]:
np.random.random_sample(d.shape)

array([[[0.92397552, 0.02262184],
        [0.60646925, 0.48517749]],

       [[0.12221006, 0.40267458],
        [0.08959186, 0.36490167]]])

In [75]:
# Random Integers 
np.random.randint(-4, 7, size=(3,3))

array([[ 6,  4, -4],
       [ 0,  4, -1],
       [-3, -4,  6]])

In [76]:
# Identty Matrix  (By nature it will be a square 2D matrix)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3,axis = 0)   #see the documentation for the entire info on numpy.repeat function
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
# How to create this matrix : 
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 0 0 0 1
# 1 1 1 1 1
# By following the steps below :

# Creating ones matrix
output = np.ones((5,5), dtype="int32")
print(output, '\n')

# Creating 3x3 0s matrix and making the middle element 9
z = np.zeros((3,3))
z[1,1] = 9
print(z,'\n')

# Finally replacing the middle part of the 1s matrix with z
output[1:-1 , 1:-1] = z # from the first element to the last element
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


##### Be careful while copying arrays

In [8]:
a = np.array([1,2,3])   
b = a.copy()  
b[0] =  100
print("b : ",b)
print("a : ",a)

b :  [100   2   3]
a :  [1 2 3]


# Mathematics

In [10]:
# a = [1,2,3]
a + 2  

array([3, 4, 5])

In [14]:
a - 2 

array([-1,  0,  1])

In [15]:
a * 2

array([2, 4, 6])

In [16]:
a / 2

array([0.5, 1. , 1.5])

In [17]:
a += 2 
print(a)

[3 4 5]


In [18]:
a ** 2

array([ 9, 16, 25])

In [20]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427])

# Linear Algebra

In [23]:
a = np.ones((2,3))
print(a, '\n')

b = np.full((3,2), 2)
print(b,'\n')

# Since a is 2x3 and b is 3x2 .... so array multiplication is possible!
np.matmul(a,b)  # Matrix Multiplication method using numpy library function

[[1. 1. 1.]
 [1. 1. 1.]] 

[[2 2]
 [2 2]
 [2 2]] 



array([[6., 6.],
       [6., 6.]])

In [3]:
# Find the determinent
c = np.identity(3)
np.linalg.det(c)        # linear algorithm module of numpy libary

1.0